FROM --platform=linux/amd64 node:20-slim

WORKDIR /app/frontend

# Install dependencies first (utilizing Docker cache)
COPY frontend/package*.json ./
RUN npm install

# Copy the frontend directory
COPY frontend/ .


CMD ["npm", "run", "start"] 