services:

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./api/instagram-images:/var/www/instagram-images:ro
    depends_on:
      - frontend
      - api
    networks:
      - vpc_local

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src/:/tournois-tt/frontend/src
      - ./frontend/public/:/tournois-tt/frontend/public
      - ./frontend/package.json/:/tournois-tt/frontend/package.json
      - ./frontend/package-lock.json/:/tournois-tt/frontend/package-lock.json
      - ./frontend/tsconfig.json/:/tournois-tt/frontend/tsconfig.json
      - ./frontend/webpack.dev.js/:/tournois-tt/frontend/webpack.dev.js
    expose:
      - 3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    networks:
      - vpc_local

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api/:/go/src/tournois-tt/api
      - /dev/shm:/dev/shm
    expose:
      - 8080
    environment:
      - GIN_MODE=${GIN_MODE}
      - GOOGLE_GEOCODING_API_KEY=${GOOGLE_GEOCODING_API_KEY}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - BREVO_CAMPAIGN_ID=${BREVO_CAMPAIGN_ID}
      - PLAYWRIGHT_BROWSERS_PATH=/usr/local/ms-playwright
      - CONTAINER_RUNTIME=1
      - DISPLAY=:99
      - XDG_RUNTIME_DIR=/tmp/runtime-dir
      - GA_MEASUREMENT_ID=${GA_MEASUREMENT_ID}
      - GA_API_SECRET=${GA_API_SECRET}
      - INSTAGRAM_ENABLED=${INSTAGRAM_ENABLED}
      - INSTAGRAM_ACCESS_TOKEN=${INSTAGRAM_ACCESS_TOKEN}
      - INSTAGRAM_PAGE_ID=${INSTAGRAM_PAGE_ID}
    networks:
      - vpc_local
    cap_add:
      - SYS_ADMIN
    shm_size: 2gb

networks:
  vpc_local:
    driver: bridge 