FROM mcr.microsoft.com/playwright:v1.52.0-jammy

# Install Go
RUN apt-get update && apt-get install -y wget
RUN wget https://go.dev/dl/go1.24.3.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.24.3.linux-amd64.tar.gz && \
    rm go1.24.3.linux-amd64.tar.gz
ENV PATH=$PATH:/usr/local/go/bin:/go/bin:/root/go/bin

WORKDIR /go/src/tournois-tt/api

COPY . .

RUN go mod tidy

ENV PLAYWRIGHT_BROWSERS_PATH=/usr/local/ms-playwright
RUN go run github.com/playwright-community/playwright-go/cmd/playwright@v0.5200.1 install

RUN go install github.com/air-verse/air@latest

COPY entrypoint-dev.sh /entrypoint-dev.sh
RUN chmod +x /entrypoint-dev.sh

ENTRYPOINT ["/entrypoint-dev.sh"]
CMD ["air", "-c", "air.toml"]